/**
 * Generated by scripts/gen_zod.js
 * Do not edit manually.
 */
import { z } from 'zod';

export const AuthorBaseSchema = z.object({ "name": z.string(), "bio": z.union([z.string(), z.null()]).default(null), "email": z.string().email() });
export type AuthorBase = z.infer<typeof AuthorBaseSchema>;

export const AuthorCreateSchema = z.object({ "name": z.string(), "bio": z.union([z.string(), z.null()]).default(null), "email": z.string().email() });
export type AuthorCreate = z.infer<typeof AuthorCreateSchema>;

export const AuthorResponseSchema = z.object({ "name": z.string(), "bio": z.union([z.string(), z.null()]).default(null), "email": z.string().email(), "id": z.number().int() });
export type AuthorResponse = z.infer<typeof AuthorResponseSchema>;

export const PaperBaseSchema = z.object({ "title": z.string(), "abstract": z.union([z.string(), z.null()]).default(null), "doi": z.string(), "author_id": z.number().int() });
export type PaperBase = z.infer<typeof PaperBaseSchema>;

export const PaperCreateSchema = z.object({ "title": z.string(), "abstract": z.union([z.string(), z.null()]).default(null), "doi": z.string(), "author_id": z.number().int() });
export type PaperCreate = z.infer<typeof PaperCreateSchema>;

export const PaperResponseSchema = z.object({ "title": z.string(), "abstract": z.union([z.string(), z.null()]).default(null), "doi": z.string(), "author_id": z.number().int(), "id": z.number().int() });
export type PaperResponse = z.infer<typeof PaperResponseSchema>;

