const fs = require('fs');
const path = require('path');
const { jsonSchemaToZod } = require('json-schema-to-zod');

// Input: OpenAPI Spec
const SCHEMA_PATH = path.join(__dirname, '../../frontend/specs/openapi.json');
const OUTPUT_FILE = path.join(__dirname, '../src/lib/api/schemas.ts');

async function generate() {
  if (!fs.existsSync(SCHEMA_PATH)) {
    console.error(`Schema file not found: ${SCHEMA_PATH}`);
    process.exit(1);
  }

  const spec = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf-8'));
  
  // Extract schemas from OpenAPI components
  const definitions = spec.components?.schemas;

  if (!definitions) {
    console.error("No schemas found in components.schemas.");
    process.exit(1);
  }

  // Header
  let fileContent = `/**
 * Generated by scripts/gen_zod.js
 * Do not edit manually.
 */
import { z } from 'zod';

`;

  for (const [key, definition] of Object.entries(definitions)) {
    try {
      // 1. Naming: Strip 'DTO' suffix to match Frontend conventions
      const cleanKey = key.replace(/DTO$/, '');
            // 2. Generate Zod Schema
      // module: "none" returns raw Zod object without exports/imports
      const zodSchema = jsonSchemaToZod(definition, { 
        module: "none",
        // name: cleanKey, // Removing name to get just the expression
        type: false, // We generate types manually below
        noImport: true,
        // Even if no refs are currently used, passing definitions context is good practice
        definitions: definitions, 
        definitionPath: "components/schemas",
      });

      // 3. Append to file
      const schemaWithTrim = zodSchema.replace(/z\.string\(\)/g, "z.string().trim()");
      
      fileContent += `export const ${cleanKey}Schema = ${schemaWithTrim};\n`;
      fileContent += `export type ${cleanKey} = z.infer<typeof ${cleanKey}Schema>;\n\n`;
      
      console.log(`Converted ${key} -> ${cleanKey}`);
    } catch (e) {
      console.error(`Error converting ${key}:`, e);
    }
  }

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`\n Schemas written to ${OUTPUT_FILE}`);
}

generate();
